=== uo289521/final/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre_circuito" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="horaEspaña" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre_circuito" type="xs:string" />
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="medida" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="medida" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	 <xs:element name="fecha" type="xs:date" />
	<xs:element name="horaEspaña" type="xs:time" />
	<xs:element name="numeroVueltas" type="xs:positiveInteger" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
    	<xs:complexType>
        	<xs:simpleContent>
            	<xs:extension base="xs:string">
                	<xs:attribute name="formato" type="xs:string" use="required" />
            	</xs:extension>
       	 	</xs:simpleContent>
    	</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:double" />
	<xs:element name="latitud" type="xs:double" />
	<xs:element name="altitud" type="xs:double" />
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenada" />
				<xs:element ref="numero-sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="numero-sector" >
		<xs:simpleType>
			<xs:restriction base = "xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== uo289521/final/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <circuito>
        <nombre_circuito>Circuito de Catalunya</nombre_circuito>

        <longitudCircuito medida="Metro">4627</longitudCircuito>

        <anchura medida="Metro">12</anchura>

        <fecha>2024-06-23</fecha>

        <horaEspaña>15:00:00</horaEspaña>

        <numeroVueltas>66</numeroVueltas>

        <localidad>Montmello</localidad>

        <pais>España</pais>

        <referencias>
            <referencia>https://www.marca.com/motor/formula1/gp-espana/2023/06/04/05_0501_20230604_8_1-directo.html/</referencia>
            <referencia>https://es.wikipedia.org/wiki/Gran_Premio_de_Espa%C3%B1a</referencia>
            <referencia>https://www.circuitcat.com/es/formula-1/</referencia>
        </referencias>

        <fotografias>
            <fotografia>xml/23011300009.jpg</fotografia>
            <fotografia>xml/FotoAerea_2021.jpg</fotografia>
            <fotografia>xml/circuit-de-catalunya-2023.jpeg</fotografia>
        </fotografias>

        <videos>
            <video formato="mp4">xml/AdelantamientoMontmello.mp4</video>
        </videos>
        <coordenadas>
            <coordenada>
                <longitud>41</longitud>
                <latitud>2.261111111111111</latitud>
                <altitud>121</altitud>
            </coordenada>
        </coordenadas>

        <tramos>

           <tramo>
                <distancia unidad="Metro">703</distancia>
                <coordenada>
                    <longitud>2.256699730797056</longitud>
                    <latitud>41.56466885543131</latitud>
                    <altitud>115</altitud>
                </coordenada>
                <numero-sector>1</numero-sector>
           </tramo>

           <tramo>
                <distancia unidad="Metro">34</distancia>
                <coordenada>
                    <longitud>2.256303383075653</longitud>
                    <latitud>41.5646339622560</latitud>
                    <altitud>115</altitud>               
                </coordenada>
                <numero-sector>1</numero-sector>
           </tramo>
        
           <tramo>
            <distancia unidad="Metro">65</distancia>
            <coordenada>
                <longitud>2.256303383075653</longitud>
                <latitud>41.564633962256</latitud>
                <altitud>115</altitud>               
            </coordenada>
            <numero-sector>1</numero-sector>
             </tramo>

            <tramo>
                <distancia unidad="Metro">131</distancia>
                <coordenada>
                    <longitud>2.253790448748028</longitud>
                    <latitud>41.5641840285645</latitud>
                    <altitud>125</altitud>               
                </coordenada>
                <numero-sector>1</numero-sector>
            </tramo>
                
            <tramo>
                <distancia unidad="Metro">90</distancia>
                <coordenada>
                    <longitud>2.252746811972048</longitud>
                    <latitud>41.56435908666257</latitud>
                    <altitud>123</altitud>               
                </coordenada>
                <numero-sector>1</numero-sector>
            </tramo>   


            <tramo>
                <distancia unidad="Metro">148</distancia>
                <coordenada>
                    <longitud>2.252118763855515</longitud>
                    <latitud>41.56558935235253</latitud>
                    <altitud>128</altitud>               
                </coordenada>
                <numero-sector>1</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">355</distancia>
                <coordenada>
                    <longitud>2.254209201450661</longitud>
                    <latitud>41.56836867952912</latitud>
                    <altitud>132</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">71</distancia>
                <coordenada>
                    <longitud>2.255035970111294</longitud>
                    <latitud>41.5683035949097</latitud>
                    <altitud>136</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">94</distancia>
                <coordenada>
                    <longitud>2.255417840448666</longitud>
                    <latitud>41.56750650013978</latitud>
                    <altitud>133</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">230</distancia>
                <coordenada>
                    <longitud>2.254001251029978</longitud>
                    <latitud>41.56572791000535</latitud>
                    <altitud>130</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">42</distancia>
                <coordenada>
                    <longitud>2.254151804130125</longitud>
                    <latitud>41.56536779615914</latitud>
                    <altitud>127</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">49</distancia>
                <coordenada>
                    <longitud>2.254738700037278</longitud>
                    <latitud>41.56536779615914</latitud>
                    <altitud>119</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">170</distancia>
                <coordenada>
                    <longitud>2.256586576848785</longitud>
                    <latitud>41.56606474086738</latitud>
                    <altitud>116</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">103</distancia>
                <coordenada>
                    <longitud>2.256958521682597</longitud>
                    <latitud>41.56806040570471</latitud>
                    <altitud>125</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">243</distancia>
                <coordenada>
                    <longitud>2.25598551302717</longitud>
                    <latitud>41.57012465357101</latitud>
                    <altitud>135</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">62</distancia>
                <coordenada>
                    <longitud>2.256386497689324</longitud>
                    <latitud>41.57060084861243</latitud>
                    <altitud>134</altitud>               
                </coordenada>
                <numero-sector>2</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">520</distancia>
                <coordenada>
                    <longitud>2.261942589257551</longitud>
                    <latitud>41.57274336844465</latitud>
                    <altitud>126</altitud>               
                </coordenada>
                <numero-sector>3</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">53</distancia>
                <coordenada>
                    <longitud>2.26184186575767</longitud>
                    <latitud>41.57321309635011</latitud>
                    <altitud>130</altitud>               
                </coordenada>
                <numero-sector>3</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">96</distancia>
                <coordenada>
                    <longitud>2.260712833775804</longitud>
                    <latitud>41.57337768809314</latitud>
                    <altitud>132</altitud>               
                </coordenada>
                <numero-sector>3</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">95</distancia>
                <coordenada>
                    <longitud>2.259801830203805</longitud>
                    <latitud>41.57286780396559</latitud>
                    <altitud>135</altitud>               
                </coordenada>
                <numero-sector>3</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">67</distancia>
                <coordenada>
                    <longitud>2.259038988570903</longitud>
                    <latitud>41.57305935330928</latitud>
                    <altitud>140</altitud>               
                </coordenada>
                <numero-sector>3</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">81</distancia>
                <coordenada>
                    <longitud>2.259127872735052</longitud>
                    <latitud>41.57378594041764</latitud>
                    <altitud>146</altitud>               
                </coordenada>
                <numero-sector>3</numero-sector>
            </tramo> 

            <tramo>
                <distancia unidad="Metro">172</distancia>
